name: CI

on: [push]

jobs:
  test:
    name: Test on node ${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    strategy:
      fail-fast: true
      matrix:
        node: [8, 10, 12]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Use node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org
      - name: install
        run: npm install
      - name: lint
        # Prettier runs are disabled on node 8 as prettier >v2 doesn't support this env
        if: matrix.node != 8
        run: npm run lint
      - name: build
        run: npm run build
      - name: install chromium
        run: npm run chromium
      - name: test
        run: npm test
        env:
          FORCE_EXIT: true
